name: 'PR Pusher - RopePusher'
description: 'Retries check-runs until they succeeds'
inputs:
  retries:
    description: 'Max number of retries to attempt for each check-run.'
  auth_token:
    description: 'The token used to authenticate to GitHub.'

runs:
  using: 'node12'
  main: 'ropepusher.js'
